require("packer-config")
require("settings")
require("mappings")
require("colorschemes-config.nightfox")
require("nvim-tree-config")
require("lualine-config")
require("treesitter-config")
require("colorizer-config")
-- require("cmp-config")
require("filetype-config")
require("telescope-config")

